# Generated by Django 4.2.16 on 2025-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/webservices/')),
            ],
        ),
    ]
